export default {
  RECEIVED_EVENTS: 'RECEIVED_EVENTS',
  RECEIVED_ONE_EVENT: 'RECEIVED_ONE_EVENT',
  RECEIVED_ONE_PARTICIPANT: 'RECEIVED_ONE_PARTICIPANT',
  REMOVED_ONE_PARTICIPANT: 'REMOVED_ONE_PARTICIPANT',
  RECEIVED_USERS: 'RECEIVED_USERS',
  RECEIVED_ONE_FOLLOWER: 'RECEIVED_ONE_FOLLOWER',
  RECEIVED_COMMENTS: 'RECEIVED_COMMENTS',
  RECEIVED_ONE_COMMENT: 'RECEIVED_ONE_COMMENT',
}
